# Generated by vibing.py
def generate_fibonacci(n):
    return [0, 1] + [generate_fibonacci(n - 1)[-1] + generate_fibonacci(n - 2)[-1] for _ in range(n - 1)]

# Usage
print(generate_fibonacci(10))  # Output: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
name = input("Enter your name: ")
print(f"Hello, {name}!")
